#!/usr/bin/env node
var fs = require('fs')
var path = require('path')
var cp = require('child_process')

var cmd = ['webpack-dev-server ']

cmd = cmd.concat(['--inline'])
cmd = cmd.concat(['--content-base', 'build/'])
cmd = cmd.concat(['--config', '../webpack.common.js'])
cmd = cmd.concat(['--port', 8080])
cmd = cmd.concat(['--history-api-fallback', '--hot'])

cp.execSync(cmd.join(' '), {
  cwd: path.join(process.cwd(), 'main', '0.simple'),
  stdio: [process.stdin, process.stdout, process.stderr]
})